language: node_js
sudo: false
node_js:
  - node
  - 6
  - 7

services:
  - mongodb

env:
  PORT=3001

install:
  - npm install
  - cp ./config/default.js.dist ./config/default.js

script:
  - npm test